apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "texas.fullname" . }}-worker
  labels:
    {{- include "texas.celeryWorker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.celeryWorker.autoscaling.enabled }}
  replicas: {{ .Values.celeryWorker.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "texas.celeryWorker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.celeryWorker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "texas.celeryWorker.labels" . | nindent 8 }}
        {{- with .Values.celeryWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.celeryWorker.terminationGracePeriodSeconds | default 120 }}
      containers:
        - name: celery-worker
          image: {{ include "texas.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ROLE
              value: "worker"
            # -- 敏感信息 --
            {{- if .Values.postgresql.enabled }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "texas.secretName" . }}
                  key: POSTGRES_PASSWORD
            {{- end }}
            {{- if (index .Values "redis-broker" "enabled") }}
            - name: REDIS_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "texas.secretName" . }}
                  key: REDIS_BROKER_PASSWORD
            {{- end }}
            {{- if (index .Values "redis-cache" "enabled") }}
            - name: REDIS_CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "texas.secretName" . }}
                  key: REDIS_CACHE_PASSWORD
            {{- end }}
            # -- 构建的连接 URL --
            - name: DATABASE_URL
              value: {{ include "texas.databaseUrl" . | quote }}
            - name: CELERY_BROKER_URL
              value: {{ include "texas.celeryBrokerUrl" . | quote }}
            - name: CACHE_REDIS_URL
              value: {{ include "texas.cacheRedisUrl" . | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "texas.configMapName" . }}
          resources:
            {{- toYaml .Values.celeryWorker.resources | nindent 12 }}
      {{- with .Values.celeryWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

