apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "texas.fullname" . }}-beat
  labels:
    {{- include "texas.celeryBeat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.celeryBeat.replicaCount }}
  # Recreate 策略，避免重复调度
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "texas.celeryBeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.celeryBeat.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "texas.celeryBeat.labels" . | nindent 8 }}
        {{- with .Values.celeryBeat.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celery-beat
          image: {{ include "texas.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ROLE
              value: "beat"
            # -- 敏感信息 --
            {{- if (index .Values "redis-broker" "enabled") }}
            - name: REDIS_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "texas.secretName" . }}
                  key: REDIS_BROKER_PASSWORD
            {{- end }}
            # -- 构建的连接 URL --
            - name: CELERY_BROKER_URL
              value: {{ include "texas.celeryBrokerUrl" . | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "texas.configMapName" . }}
          resources:
            {{- toYaml .Values.celeryBeat.resources | nindent 12 }}
      {{- with .Values.celeryBeat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryBeat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryBeat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

