{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "texas.fullname" . }}
  labels:
    {{- include "texas.labels" . | nindent 4 }}
type: Opaque
data:
  NAPCAT_ACCESS_TOKEN: {{ (.Values.secrets.napcatAccessToken | default .Values.napcat.accessToken) | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ (.Values.secrets.postgresPassword | default .Values.postgresql.auth.password) | b64enc | quote }}
  {{- end }}
  {{- if (index .Values "redis-broker" "enabled") }}
  REDIS_BROKER_PASSWORD: {{ (.Values.secrets.redisBrokerPassword | default (index .Values "redis-broker" "auth" "password")) | b64enc | quote }}
  {{- end }}
  {{- if (index .Values "redis-cache" "enabled") }}
  REDIS_CACHE_PASSWORD: {{ (.Values.secrets.redisCachePassword | default (index .Values "redis-cache" "auth" "password")) | b64enc | quote }}
  {{- end }}
{{- end }}

