"""auto

Revision ID: 99895e523017
Revises: b7a85e8cab15
Create Date: 2026-04-14 11:18:42.742044

"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99895e523017"
down_revision: str | None = "b7a85e8cab15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permission_group",
        "group_id",
        existing_type=sa.BIGINT(),
        comment="群号（0 为全局哨兵行）",
        existing_comment="群号",
        existing_nullable=False,
    )
    op.alter_column(
        "permission_private",
        "enabled",
        existing_type=sa.BOOLEAN(),
        comment="是否允许该用户私聊使用此功能",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permission_private",
        "enabled",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="是否允许该用户私聊使用此功能",
        existing_nullable=False,
    )
    op.alter_column(
        "permission_group",
        "group_id",
        existing_type=sa.BIGINT(),
        comment="群号",
        existing_comment="群号（0 为全局哨兵行）",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
