"""auto

Revision ID: e2d880c45b41
Revises: d3f1a9c72e05
Create Date: 2026-04-18 14:22:41.680062

"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e2d880c45b41"
down_revision: str | None = "d3f1a9c72e05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkin",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False, comment="群号"),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="签到用户 QQ"),
        sa.Column(
            "checkin_date", sa.Date(), nullable=False, comment="北京时间自然日，如 2026-04-17"
        ),
        sa.Column(
            "checkin_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="精确签到时间（UTC），用于今日排名排序",
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.group_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.qq"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "group_id", "user_id", "checkin_date", name="uq_checkin_group_user_date"
        ),
    )
    op.create_index(
        "idx_checkin_user_group", "checkin", ["user_id", "group_id", "checkin_date"], unique=False
    )
    op.create_index(op.f("ix_checkin_checkin_date"), "checkin", ["checkin_date"], unique=False)
    op.create_index(op.f("ix_checkin_group_id"), "checkin", ["group_id"], unique=False)
    op.alter_column(
        "like_history",
        "qq",
        existing_type=sa.BIGINT(),
        comment="被点赞对象 QQ（无外键约束）",
        existing_nullable=False,
    )
    op.alter_column(
        "like_history",
        "times",
        existing_type=sa.SMALLINT(),
        comment="本次点赞次数",
        existing_nullable=False,
    )
    op.alter_column(
        "like_history",
        "triggered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="执行时间（UTC）",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "like_history",
        "source",
        existing_type=postgresql.ENUM("manual", "scheduled", name="likesource"),
        comment="触发来源：manual=手动，scheduled=定时",
        existing_nullable=False,
    )
    op.alter_column(
        "like_history",
        "success",
        existing_type=sa.BOOLEAN(),
        comment="是否成功",
        existing_nullable=False,
    )
    op.alter_column(
        "like_tasks",
        "qq",
        existing_type=sa.BIGINT(),
        comment="被点赞用户 QQ（无外键约束，全局唯一）",
        existing_nullable=False,
    )
    op.alter_column(
        "like_tasks",
        "registered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="注册时间（UTC）",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "like_tasks",
        "registered_group_id",
        existing_type=sa.BIGINT(),
        comment="注册时所在群（私聊注册为 null），仅记录来源，不影响执行",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "like_tasks",
        "registered_group_id",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="注册时所在群（私聊注册为 null），仅记录来源，不影响执行",
        existing_nullable=True,
    )
    op.alter_column(
        "like_tasks",
        "registered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="注册时间（UTC）",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "like_tasks",
        "qq",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="被点赞用户 QQ（无外键约束，全局唯一）",
        existing_nullable=False,
    )
    op.alter_column(
        "like_history",
        "success",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="是否成功",
        existing_nullable=False,
    )
    op.alter_column(
        "like_history",
        "source",
        existing_type=postgresql.ENUM("manual", "scheduled", name="likesource"),
        comment=None,
        existing_comment="触发来源：manual=手动，scheduled=定时",
        existing_nullable=False,
    )
    op.alter_column(
        "like_history",
        "triggered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="执行时间（UTC）",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "like_history",
        "times",
        existing_type=sa.SMALLINT(),
        comment=None,
        existing_comment="本次点赞次数",
        existing_nullable=False,
    )
    op.alter_column(
        "like_history",
        "qq",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="被点赞对象 QQ（无外键约束）",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_checkin_group_id"), table_name="checkin")
    op.drop_index(op.f("ix_checkin_checkin_date"), table_name="checkin")
    op.drop_index("idx_checkin_user_group", table_name="checkin")
    op.drop_table("checkin")
    # ### end Alembic commands ###
