"""auto

Revision ID: 020e8c8bee06
Revises: 0e27afd61559
Create Date: 2026-03-10 09:40:37.415294

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020e8c8bee06"
down_revision: str | None = "0e27afd61559"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_providers", "is_enabled")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "llm_providers",
        sa.Column(
            "is_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False, comment="是否启用"
        ),
    )
    # ### end Alembic commands ###
