"""auto

Revision ID: 08c4784ae3bd
Revises: ce80018b74df
Create Date: 2026-03-10 09:16:07.358739

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "08c4784ae3bd"
down_revision: str | None = "ce80018b74df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False, comment="提供商名称"),
        sa.Column("api_base", sa.String(length=512), nullable=False, comment="API 基础地址"),
        sa.Column("api_key", sa.String(length=512), nullable=False, comment="API 密钥"),
        sa.Column("is_enabled", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "llms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False, comment="所属提供商"),
        sa.Column("model_name", sa.String(length=128), nullable=False, comment="模型标识"),
        sa.Column("display_name", sa.String(length=128), nullable=True, comment="展示名称"),
        sa.Column(
            "input_price",
            sa.Numeric(precision=12, scale=6),
            nullable=False,
            comment="输入价格 (每百万 token, USD)",
        ),
        sa.Column(
            "output_price",
            sa.Numeric(precision=12, scale=6),
            nullable=False,
            comment="输出价格 (每百万 token, USD)",
        ),
        sa.Column("temperature", sa.Float(), nullable=False, comment="默认温度"),
        sa.Column("max_tokens", sa.Integer(), nullable=True, comment="最大输出 token 数"),
        sa.Column("force_stream", sa.Boolean(), nullable=False, comment="是否强制流式输出"),
        sa.Column(
            "extra_params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="额外请求参数",
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "model_name", name="uq_provider_model"),
    )
    op.create_index(op.f("ix_llms_provider_id"), "llms", ["provider_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llms_provider_id"), table_name="llms")
    op.drop_table("llms")
    op.drop_table("llm_providers")
    # ### end Alembic commands ###
