"""auto

Revision ID: 0e27afd61559
Revises: 08c4784ae3bd
Create Date: 2026-03-10 09:31:40.230091

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e27afd61559'
down_revision: str | None = '08c4784ae3bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('max_retries', sa.Integer(), nullable=False, comment='最大重试次数'))
    op.add_column('llm_providers', sa.Column('timeout', sa.Integer(), nullable=False, comment='请求超时 (秒)'))
    op.add_column('llm_providers', sa.Column('retry_interval', sa.Integer(), nullable=False, comment='重试间隔 (秒)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_providers', 'retry_interval')
    op.drop_column('llm_providers', 'timeout')
    op.drop_column('llm_providers', 'max_retries')
    # ### end Alembic commands ###

