"""auto

Revision ID: 3f99df445cc2
Revises: 020e8c8bee06
Create Date: 2026-03-10 11:03:16.200532

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f99df445cc2"
down_revision: Union[str, None] = "020e8c8bee06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 这两列在旧 DB 中存在但新建 DB 中不存在，使用 IF EXISTS 避免全新库启动报错。
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_cols = {c["name"] for c in inspector.get_columns("group_memberships")}
    if "created_at" in existing_cols:
        op.drop_column("group_memberships", "created_at")
    if "updated_at" in existing_cols:
        op.drop_column("group_memberships", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_memberships",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "group_memberships",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
