"""auto

Revision ID: 87ab7d887fb4
Revises: 3f99df445cc2
Create Date: 2026-03-10 14:13:22.675006

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87ab7d887fb4"
down_revision: Union[str, None] = "3f99df445cc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "llms",
        "input_price",
        existing_type=sa.NUMERIC(precision=12, scale=6),
        comment="输入价格 (每百万 token, CNY)",
        existing_comment="输入价格 (每百万 token, USD)",
        existing_nullable=False,
    )
    op.alter_column(
        "llms",
        "output_price",
        existing_type=sa.NUMERIC(precision=12, scale=6),
        comment="输出价格 (每百万 token, CNY)",
        existing_comment="输出价格 (每百万 token, USD)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "llms",
        "output_price",
        existing_type=sa.NUMERIC(precision=12, scale=6),
        comment="输出价格 (每百万 token, USD)",
        existing_comment="输出价格 (每百万 token, CNY)",
        existing_nullable=False,
    )
    op.alter_column(
        "llms",
        "input_price",
        existing_type=sa.NUMERIC(precision=12, scale=6),
        comment="输入价格 (每百万 token, USD)",
        existing_comment="输入价格 (每百万 token, CNY)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
