"""auto

Revision ID: 9216a3aa4a32
Revises:
Create Date: 2026-03-09 17:38:48.955240

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9216a3aa4a32"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_logs_group_id"), table_name="message_logs")
    op.drop_index(op.f("ix_message_logs_message_id"), table_name="message_logs")
    op.drop_index(op.f("ix_message_logs_user_id"), table_name="message_logs")
    op.drop_table("message_logs")
    op.drop_index(op.f("ix_users_qq_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_groups_group_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_handler_data_handler_name"), table_name="handler_data")
    op.drop_table("handler_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "handler_data",
        sa.Column("handler_name", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "value", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
        sa.Column("scope", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("scope_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("handler_data_pkey")),
        sa.UniqueConstraint(
            "handler_name",
            "key",
            "scope",
            "scope_id",
            name=op.f("uq_handler_data"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_handler_data_handler_name"), "handler_data", ["handler_name"], unique=False
    )
    op.create_table(
        "groups",
        sa.Column("group_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("group_name", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column("is_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "config", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("groups_pkey")),
    )
    op.create_index(op.f("ix_groups_group_id"), "groups", ["group_id"], unique=True)
    op.create_table(
        "users",
        sa.Column("qq_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("nickname", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("permission_level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_blocked", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "extra_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_qq_id"), "users", ["qq_id"], unique=True)
    op.create_table(
        "message_logs",
        sa.Column("message_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("message_type", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("raw_message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("message_logs_pkey")),
    )
    op.create_index(op.f("ix_message_logs_user_id"), "message_logs", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_message_logs_message_id"), "message_logs", ["message_id"], unique=False
    )
    op.create_index(op.f("ix_message_logs_group_id"), "message_logs", ["group_id"], unique=False)
    # ### end Alembic commands ###
