"""auto

Revision ID: c352f39d1de8
Revises: a1b2c3d4e5f6
Create Date: 2026-03-25 11:21:33.147129

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c352f39d1de8"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "feature_registry",
        "parent",
        existing_type=sa.VARCHAR(length=64),
        comment="父功能（controller 级为 null，method 级指向 controller）",
        existing_comment="父功能",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_registry",
        "display_name",
        existing_type=sa.VARCHAR(length=128),
        comment="显示名称（命令名、描述等）",
        existing_comment="显示名称",
        existing_nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "feature_registry",
        "default_enabled",
        existing_type=sa.BOOLEAN(),
        comment="装饰器声明的默认启用状态",
        existing_comment="默认启用状态",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "feature_registry",
        "enabled",
        existing_type=sa.BOOLEAN(),
        comment="全局开关（管理员可修改）",
        existing_comment="全局开关",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "feature_registry",
        "private_mode",
        existing_type=sa.VARCHAR(length=16),
        comment="私聊权限模式: blacklist/whitelist",
        existing_comment="私聊模式",
        existing_nullable=False,
        existing_server_default=sa.text("'blacklist'::character varying"),
    )
    op.alter_column(
        "feature_registry",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="功能是否仍在代码中存在",
        existing_comment="是否活跃",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "group_feature_permissions",
        "feature_name",
        existing_type=sa.VARCHAR(length=64),
        comment="功能标识（controller 或 method 级）",
        existing_comment="功能标识",
        existing_nullable=False,
    )
    op.alter_column(
        "private_feature_permissions",
        "feature_name",
        existing_type=sa.VARCHAR(length=64),
        comment="功能标识（controller 级）",
        existing_comment="功能标识",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "private_feature_permissions",
        "feature_name",
        existing_type=sa.VARCHAR(length=64),
        comment="功能标识",
        existing_comment="功能标识（controller 级）",
        existing_nullable=False,
    )
    op.alter_column(
        "group_feature_permissions",
        "feature_name",
        existing_type=sa.VARCHAR(length=64),
        comment="功能标识",
        existing_comment="功能标识（controller 或 method 级）",
        existing_nullable=False,
    )
    op.alter_column(
        "feature_registry",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="是否活跃",
        existing_comment="功能是否仍在代码中存在",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "feature_registry",
        "private_mode",
        existing_type=sa.VARCHAR(length=16),
        comment="私聊模式",
        existing_comment="私聊权限模式: blacklist/whitelist",
        existing_nullable=False,
        existing_server_default=sa.text("'blacklist'::character varying"),
    )
    op.alter_column(
        "feature_registry",
        "enabled",
        existing_type=sa.BOOLEAN(),
        comment="全局开关",
        existing_comment="全局开关（管理员可修改）",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "feature_registry",
        "default_enabled",
        existing_type=sa.BOOLEAN(),
        comment="默认启用状态",
        existing_comment="装饰器声明的默认启用状态",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "feature_registry",
        "display_name",
        existing_type=sa.VARCHAR(length=128),
        comment="显示名称",
        existing_comment="显示名称（命令名、描述等）",
        existing_nullable=False,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "feature_registry",
        "parent",
        existing_type=sa.VARCHAR(length=64),
        comment="父功能",
        existing_comment="父功能（controller 级为 null，method 级指向 controller）",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
