"""auto

Revision ID: ca4d83f14568
Revises: 87ab7d887fb4
Create Date: 2026-03-10 16:22:22.287422

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca4d83f14568'
down_revision: Union[str, None] = '87ab7d887fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # chat_history 表位于 chat schema，由 alembic_chat.ini 独立管理，此处不再创建。
    op.create_table('chat_archive_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partition_name', sa.String(length=64), nullable=False, comment='分区表名，如 chat_history_2024_01'),
    sa.Column('period_start', sa.Date(), nullable=False, comment='归档周期起始日期'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='归档周期结束日期'),
    sa.Column('total_rows', sa.BigInteger(), nullable=False, comment='归档行数'),
    sa.Column('original_bytes', sa.BigInteger(), nullable=False, comment='原始数据大小（字节）'),
    sa.Column('compressed_bytes', sa.BigInteger(), nullable=False, comment='压缩后大小（字节）'),
    sa.Column('s3_bucket', sa.String(length=128), nullable=False, comment='S3 桶名'),
    sa.Column('s3_key', sa.String(length=512), nullable=False, comment='S3 对象键'),
    sa.Column('s3_sha256', sa.String(length=64), nullable=False, comment='归档文件 SHA256'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='归档状态: pending/exporting/uploading/uploaded/partition_dropped/completed/failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='NOW()', nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partition_name')
    )
    op.create_index('ix_archive_log_period', 'chat_archive_log', ['period_start'], unique=False)
    op.create_index('ix_archive_log_status', 'chat_archive_log', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_archive_log_status', table_name='chat_archive_log')
    op.drop_index('ix_archive_log_period', table_name='chat_archive_log')
    op.drop_table('chat_archive_log')
    # chat_history 表位于 chat schema，由 alembic_chat.ini 独立管理，此处不再删除。
    # ### end Alembic commands ###

