"""auto

Revision ID: ce80018b74df
Revises: 9216a3aa4a32
Create Date: 2026-03-09 22:56:45.629539

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce80018b74df'
down_revision: Union[str, None] = '9216a3aa4a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='群号'),
    sa.Column('group_name', sa.String(length=128), nullable=False, comment='群名称'),
    sa.Column('member_count', sa.Integer(), nullable=False, comment='当前成员数'),
    sa.Column('max_member_count', sa.Integer(), nullable=False, comment='最大成员数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='群聊是否活跃（机器人是否仍在群中）'),
    sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后同步时间'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_groups_is_active'), 'groups', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('qq', sa.BigInteger(), nullable=False, comment='QQ 号'),
    sa.Column('nickname', sa.String(length=64), nullable=False, comment='QQ 昵称'),
    sa.Column('relation', sa.String(length=20), nullable=False, comment='关系等级: stranger/group_member/friend/admin'),
    sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后同步时间'),
    sa.PrimaryKeyConstraint('qq')
    )
    op.create_index(op.f('ix_users_relation'), 'users', ['relation'], unique=False)
    op.create_table('group_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='关联用户 QQ 号'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='关联群号'),
    sa.Column('card', sa.String(length=64), nullable=False, comment='群名片'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='群内角色: owner/admin/member'),
    sa.Column('join_time', sa.BigInteger(), nullable=False, comment='入群时间戳'),
    sa.Column('last_active_time', sa.BigInteger(), nullable=False, comment='最后活跃时间戳'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='群头衔'),
    sa.Column('title_expire_time', sa.BigInteger(), nullable=False, comment='头衔过期时间戳'),
    sa.Column('level', sa.String(length=10), nullable=False, comment='群等级'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否仍在群中'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.qq'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group')
    )
    op.create_index(op.f('ix_group_memberships_group_id'), 'group_memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_memberships_is_active'), 'group_memberships', ['is_active'], unique=False)
    op.create_index(op.f('ix_group_memberships_user_id'), 'group_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_memberships_user_id'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_is_active'), table_name='group_memberships')
    op.drop_index(op.f('ix_group_memberships_group_id'), table_name='group_memberships')
    op.drop_table('group_memberships')
    op.drop_index(op.f('ix_users_relation'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_is_active'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###

