"""add_jrlp_table

Revision ID: cf5cf525a02a
Revises: a3f8e1b2c4d5
Create Date: 2026-04-06 14:16:43.878868

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf5cf525a02a"
down_revision: Union[str, None] = "a3f8e1b2c4d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jrlp",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False, comment="群号"),
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="抽取者 QQ"),
        sa.Column("wife_qq", sa.BigInteger(), nullable=False, comment="老婆 QQ"),
        sa.Column(
            "wife_name",
            sa.String(length=64),
            nullable=False,
            comment="老婆昵称快照（抽取时记录，防止后续改名影响历史）",
        ),
        sa.Column("date", sa.Date(), nullable=False, comment="自然日（北京时间），如 2026-04-06"),
        sa.Column(
            "drawn_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="抽取时间；null = 管理员预设未触发；有值 = 用户已抽取",
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.group_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.qq"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wife_qq"], ["users.qq"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id", "date", name="uq_jrlp_group_user_date"),
    )
    op.create_index(op.f("ix_jrlp_date"), "jrlp", ["date"], unique=False)
    op.create_index(op.f("ix_jrlp_group_id"), "jrlp", ["group_id"], unique=False)
    op.create_index(op.f("ix_jrlp_user_id"), "jrlp", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jrlp_user_id"), table_name="jrlp")
    op.drop_index(op.f("ix_jrlp_group_id"), table_name="jrlp")
    op.drop_index(op.f("ix_jrlp_date"), table_name="jrlp")
    op.drop_table("jrlp")
    # ### end Alembic commands ###
